import type { AIModel, Policy, AuditEntry, ComplianceFramework, BiasMetric, DashboardStats, UseCaseRisk, StateDisclosure, RoadmapPhase, GovernancePrinciple } from '@/types';

export const models: AIModel[] = [
  {
    id: 'm1', name: 'Symptom Triage AI', version: '2.3.1', status: 'production',
    purpose: 'Triage patient-reported symptoms for priority routing', riskLevel: 'high',
    owner: 'Clinical AI Team', deployedAt: '2025-09-15', lastAudit: '2026-02-01',
    biasScore: 18, accuracyScore: 91, fairnessScore: 87,
    fdaClass: 'CDS-non-device', euRiskTier: 'High-Risk', pccp: 'not-required',
    fhirStatus: 'live', explainabilityEnabled: true, hitlRequired: true,
  },
  {
    id: 'm2', name: 'Hormone Cycle Predictor', version: '1.8.0', status: 'production',
    purpose: 'Predict hormonal cycle phases from wearable data', riskLevel: 'medium',
    owner: 'FemTech Research', deployedAt: '2025-11-02', lastAudit: '2026-01-20',
    biasScore: 11, accuracyScore: 88, fairnessScore: 93,
    fdaClass: 'General Wellness', euRiskTier: 'Limited Risk', pccp: 'not-required',
    fhirStatus: 'live', explainabilityEnabled: true, hitlRequired: false,
  },
  {
    id: 'm3', name: 'Endometriosis Risk Scorer', version: '1.1.4', status: 'staging',
    purpose: 'Estimate endometriosis likelihood from reported symptoms', riskLevel: 'critical',
    owner: 'Clinical AI Team', deployedAt: '2026-01-10', lastAudit: '2026-02-28',
    biasScore: 31, accuracyScore: 79, fairnessScore: 74,
    fdaClass: 'SaMD', euRiskTier: 'High-Risk', pccp: 'in-progress',
    fhirStatus: 'in-progress', explainabilityEnabled: false, hitlRequired: true,
  },
  {
    id: 'm4', name: 'Mental Health Screener', version: '3.0.0', status: 'production',
    purpose: 'PHQ-9 / GAD-7 guided screening assistant', riskLevel: 'high',
    owner: 'Behavioral Health Squad', deployedAt: '2025-07-20', lastAudit: '2026-02-10',
    biasScore: 22, accuracyScore: 85, fairnessScore: 81,
    fdaClass: 'CDS-non-device', euRiskTier: 'High-Risk', pccp: 'not-required',
    fhirStatus: 'live', explainabilityEnabled: true, hitlRequired: true,
  },
  {
    id: 'm5', name: 'Nutrition Recommendation Engine', version: '2.0.2', status: 'production',
    purpose: "Personalized dietary guidance for women's health goals", riskLevel: 'low',
    owner: 'Wellness Team', deployedAt: '2025-06-01', lastAudit: '2026-01-05',
    biasScore: 7, accuracyScore: 83, fairnessScore: 95,
    fdaClass: 'General Wellness', euRiskTier: 'Minimal Risk', pccp: 'not-required',
    fhirStatus: 'planned', explainabilityEnabled: true, hitlRequired: false,
  },
];

export const policies: Policy[] = [
  {
    id: 'p1', title: 'AI Model Risk Classification Policy', category: 'Risk Management',
    status: 'active', version: '1.2', owner: 'Chief AI Officer',
    createdAt: '2025-04-01', updatedAt: '2026-01-15',
    description: 'Defines risk tiers (FDA/EU/state) for all AI models based on clinical impact, data sensitivity, and patient exposure. Maps to NIST AI RMF MAP function.',
    applicableModels: ['m1', 'm2', 'm3', 'm4', 'm5'],
    frameworks: ['NIST AI RMF', 'ISO 42001', 'EU AI Act'],
  },
  {
    id: 'p2', title: 'Bias Testing & Fairness Requirements', category: 'Fairness',
    status: 'active', version: '2.0', owner: 'Ethics & Fairness Board',
    createdAt: '2025-06-10', updatedAt: '2025-12-20',
    description: 'Mandates demographic parity, equalized odds, and calibration testing across race, gender, age, and geography before production deployment. Quarterly re-evaluation required.',
    applicableModels: ['m1', 'm3', 'm4'],
    frameworks: ['ISO 42001', 'Colorado AI Act', 'EU AI Act', 'NIST AI RMF'],
  },
  {
    id: 'p3', title: 'Patient Data Usage & Consent Policy', category: 'Privacy',
    status: 'active', version: '3.1', owner: 'Privacy & Legal',
    createdAt: '2024-11-01', updatedAt: '2026-02-01',
    description: 'Governs how patient-derived data is used for model training, inference, and retraining. Includes full data lineage documentation and California AB 2013 training data disclosure requirements.',
    applicableModels: ['m1', 'm2', 'm3', 'm4', 'm5'],
    frameworks: ['HIPAA', 'ISO 42001', 'California AB 2013', 'EU AI Act'],
  },
  {
    id: 'p4', title: 'Human-in-the-Loop Override Requirements', category: 'Human Oversight',
    status: 'active', version: '1.0', owner: 'Clinical AI Team',
    createdAt: '2025-08-15', updatedAt: '2025-08-15',
    description: 'Requires licensed clinician review for all high-risk AI recommendations before surfacing to patients. All overrides must be documented. Compliant with Illinois Psychotherapy AI Law.',
    applicableModels: ['m1', 'm3', 'm4'],
    frameworks: ['EU AI Act', 'HHS AI Strategy', 'Illinois AI Law', 'ISO 42001'],
  },
  {
    id: 'p5', title: 'Model Drift Monitoring Standard', category: 'Monitoring',
    status: 'active', version: '1.1', owner: 'MLOps Team',
    createdAt: '2025-09-01', updatedAt: '2025-11-30',
    description: 'Sets thresholds and cadence for data drift and performance degradation alerts. Post-market surveillance required under FDA PCCP and EU AI Act Article 72.',
    applicableModels: ['m1', 'm2', 'm4', 'm5'],
    frameworks: ['FDA PCCP', 'EU AI Act', 'NIST AI RMF', 'ISO 42001'],
  },
  {
    id: 'p6', title: 'Explainability Disclosure Standard', category: 'Transparency',
    status: 'draft', version: '0.3', owner: 'Product & Ethics',
    createdAt: '2026-02-01', updatedAt: '2026-03-01',
    description: 'Draft policy requiring plain-language explanations and confidence scores for every AI-driven recommendation. Clinicians must be able to see reasoning and override with documentation.',
    applicableModels: ['m1', 'm3', 'm4'],
    frameworks: ['EU AI Act', 'ISO 42001', 'HHS AI Strategy'],
  },
  {
    id: 'p7', title: 'Predetermined Change Control Plan (PCCP) Policy', category: 'Regulatory',
    status: 'active', version: '1.0', owner: 'Regulatory Affairs',
    createdAt: '2025-10-01', updatedAt: '2026-01-15',
    description: 'Requires FDA PCCP submission for any adaptive AI/ML model before deployment. Defines the performance boundary envelope within which models may adapt post-clearance without a new 510(k).',
    applicableModels: ['m3'],
    frameworks: ['FDA PCCP', 'FDA SaMD Guidance'],
  },
  {
    id: 'p8', title: 'AI Incident Response & 72-Hour Reporting Policy', category: 'Incident Response',
    status: 'active', version: '1.0', owner: 'Clinical AI Team & Legal',
    createdAt: '2025-11-01', updatedAt: '2026-02-20',
    description: 'Mandatory 72-hour reporting of significant AI performance deviations or patient harm incidents. Defines escalation path: MLOps → CAIO → C-Suite → Regulatory. Required by ISO 42001 and EU AI Act Article 73.',
    applicableModels: ['m1', 'm2', 'm3', 'm4', 'm5'],
    frameworks: ['ISO 42001', 'EU AI Act', 'HHS AI Strategy'],
  },
  {
    id: 'p9', title: 'Patient AI Disclosure Protocol', category: 'Transparency',
    status: 'active', version: '2.0', owner: 'Product & Legal',
    createdAt: '2025-12-01', updatedAt: '2026-02-15',
    description: 'Written disclosure to patients when AI influences clinical decisions. Must be provided before or at time of service. Required by Texas RAIGA (eff. Jan 1, 2026), Utah AI Policy Act, Colorado AI Act, and emerging state laws.',
    applicableModels: ['m1', 'm3', 'm4'],
    frameworks: ['Texas RAIGA', 'Utah AI Policy Act', 'Colorado AI Act', 'California TFAIA'],
  },
  {
    id: 'p10', title: 'Third-Party Vendor AI Risk Management', category: 'Vendor Risk',
    status: 'active', version: '1.0', owner: 'Procurement & Legal',
    createdAt: '2026-01-01', updatedAt: '2026-02-01',
    description: 'Requires contractual AI governance attestations from all AI-component vendors (EHR, lab analyzers, wearable platforms). Includes audit rights and HIPAA BAA requirements. Tracks ONC certification requirements for EHR vendors.',
    applicableModels: ['m1', 'm2', 'm3', 'm4', 'm5'],
    frameworks: ['HIPAA', 'ONC Certification', 'NIST AI RMF', 'ISO 42001'],
  },
  {
    id: 'p11', title: 'Security by Design & SBOM Policy', category: 'Cybersecurity',
    status: 'active', version: '1.0', owner: 'Security Team',
    createdAt: '2026-01-15', updatedAt: '2026-03-01',
    description: 'Mandates threat modeling, risk assessments, and Software Bill of Materials (SBOM) for all AI systems. Aligns with FDA 2025 premarket guidance on cybersecurity for AI-enabled medical devices.',
    applicableModels: ['m1', 'm3', 'm4'],
    frameworks: ['FDA Cybersecurity Guidance 2025', 'NIST AI RMF', 'ISO 42001'],
  },
  {
    id: 'p12', title: 'Real-World Evidence Collection Standard', category: 'Monitoring',
    status: 'draft', version: '0.2', owner: 'Clinical Research & MLOps',
    createdAt: '2026-02-15', updatedAt: '2026-03-05',
    description: 'Structures data collection to generate real-world evidence (RWE) meeting FDA 2025 wearable guidance standards: data integrity, bias mitigation, and explainability. Creates pathway to expanded regulatory recognition and CMS reimbursement.',
    applicableModels: ['m1', 'm2', 'm4', 'm5'],
    frameworks: ['FDA Wearable Guidance 2026', 'CMS ACCESS Model', 'TEMPO Pilot'],
  },
];

export const auditEntries: AuditEntry[] = [
  {
    id: 'a1', timestamp: '2026-03-11T14:32:00Z', modelId: 'm3',
    modelName: 'Endometriosis Risk Scorer',
    action: 'High-risk score surfaced without clinician review',
    actor: 'System (automated)', outcome: 'Flagged — HITL override policy violated',
    riskFlag: true, incidentReport: true, category: 'hitl',
    details: 'Patient received a CRITICAL risk score directly via app notification without required HITL review step. 72-hour incident report filed. Root cause: routing logic bypass in v1.1.4.',
  },
  {
    id: 'a2', timestamp: '2026-03-11T09:15:00Z', modelId: 'm1',
    modelName: 'Symptom Triage AI',
    action: 'Model retrained on Q1 2026 data batch',
    actor: 'MLOps Pipeline', outcome: 'Success — bias re-evaluation passed',
    riskFlag: false, incidentReport: false, category: 'performance',
    details: 'Quarterly retraining completed. Bias score improved from 21 to 18. All fairness thresholds passed across age, race, and geography subgroups.',
  },
  {
    id: 'a3', timestamp: '2026-03-10T16:45:00Z', modelId: 'm4',
    modelName: 'Mental Health Screener',
    action: 'Demographic disparity detected in PHQ-9 scoring',
    actor: 'Bias Monitor (automated)', outcome: 'Warning issued — under investigation',
    riskFlag: true, incidentReport: false, category: 'bias',
    details: 'Hispanic/Latina cohort showing 12% higher false-negative rate vs overall population. Colorado AI Act quarterly bias report due. Retraining scheduled for April 2026.',
  },
  {
    id: 'a4', timestamp: '2026-03-09T11:00:00Z', modelId: 'm2',
    modelName: 'Hormone Cycle Predictor',
    action: 'HIPAA consent audit completed — Policy P3',
    actor: 'Privacy & Legal', outcome: 'Compliant',
    riskFlag: false, incidentReport: false, category: 'compliance',
    details: 'Annual consent audit confirmed all training records have valid opt-in consent. California AB 2013 training data disclosure documented.',
  },
  {
    id: 'a5', timestamp: '2026-03-08T08:20:00Z', modelId: 'm5',
    modelName: 'Nutrition Recommendation Engine',
    action: 'Performance drift alert triggered',
    actor: 'Drift Monitor (automated)', outcome: 'Acknowledged — scheduled review',
    riskFlag: false, incidentReport: false, category: 'performance',
    details: 'Accuracy dropped 2.1% over 30 days. Within acceptable range. Scheduled for review. FHIR integration planned for Q2 2026.',
  },
  {
    id: 'a6', timestamp: '2026-03-07T14:00:00Z', modelId: 'm3',
    modelName: 'Endometriosis Risk Scorer',
    action: 'FDA PCCP pre-submission meeting held',
    actor: 'Regulatory Affairs', outcome: 'Positive — formal submission Q2 2026',
    riskFlag: false, incidentReport: false, category: 'compliance',
    details: 'FDA pre-sub meeting confirmed PCCP pathway appropriate. Formal PCCP submission targeted Q2 2026. EU AI Act conformity assessment will follow.',
  },
  {
    id: 'a7', timestamp: '2026-03-05T09:30:00Z', modelId: 'm1',
    modelName: 'Symptom Triage AI',
    action: 'Texas RAIGA AI disclosure verified at point of service',
    actor: 'Product Team', outcome: 'Compliant — disclosure shown pre-service',
    riskFlag: false, incidentReport: false, category: 'policy',
    details: 'Patient-facing disclosure updated to meet Texas RAIGA requirements (eff. Jan 1, 2026). Disclosure shown before or at time of AI-influenced service.',
  },
  {
    id: 'a8', timestamp: '2026-03-03T16:00:00Z', modelId: 'm4',
    modelName: 'Mental Health Screener',
    action: 'ISO 42001 internal audit — Clause 6.1 risk assessment',
    actor: 'CAIO Office', outcome: '3 minor non-conformities — remediation underway',
    riskFlag: false, incidentReport: false, category: 'compliance',
    details: 'Internal ISO 42001 audit completed. 3 minor NCs: (1) vendor risk attestations incomplete, (2) clinician training records not centralized, (3) incident log format needs standardization.',
  },
];

export const complianceFrameworks: ComplianceFramework[] = [
  {
    id: 'c1', name: 'HIPAA', shortName: 'HIPAA', category: 'regulation',
    jurisdiction: 'US Federal', status: 'compliant', score: 96,
    lastReview: '2026-02-15', nextReview: '2026-08-15',
    openIssues: 1, totalControls: 54, passedControls: 52, mandatory: true,
    notes: 'Strong posture. 1 open issue: vendor BAA renewal pending.',
  },
  {
    id: 'c2', name: 'FDA AI/ML SaMD Guidance + PCCP', shortName: 'FDA SaMD', category: 'regulation',
    jurisdiction: 'US Federal', status: 'at-risk', score: 71,
    lastReview: '2026-01-20', nextReview: '2026-04-20',
    openIssues: 5, totalControls: 38, passedControls: 27, mandatory: true,
    deadline: '2026-06-30',
    notes: 'PCCP for Endometriosis Scorer in progress. CDS guidance review for m1/m4 pending.',
  },
  {
    id: 'c3', name: 'EU AI Act (High-Risk)', shortName: 'EU AI Act', category: 'regulation',
    jurisdiction: 'EU', status: 'at-risk', score: 68,
    lastReview: '2026-02-28', nextReview: '2026-05-28',
    openIssues: 7, totalControls: 45, passedControls: 31, mandatory: true,
    deadline: '2027-12-31',
    notes: 'Deadline extended to Dec 2027 per Digital Omnibus Proposal. Conformity assessment prep in progress.',
  },
  {
    id: 'c4', name: 'NIST AI Risk Management Framework 1.0', shortName: 'NIST AI RMF', category: 'standard',
    jurisdiction: 'US Federal (voluntary)', status: 'compliant', score: 88,
    lastReview: '2026-01-10', nextReview: '2026-07-10',
    openIssues: 2, totalControls: 50, passedControls: 44, mandatory: false,
    notes: 'GOVERN and MAP functions strong. MEASURE still maturing for m3.',
  },
  {
    id: 'c5', name: 'ISO/IEC 42001:2023 (AI Management System)', shortName: 'ISO 42001', category: 'standard',
    jurisdiction: 'International', status: 'at-risk', score: 74,
    lastReview: '2026-03-01', nextReview: '2026-06-01',
    openIssues: 4, totalControls: 42, passedControls: 31, mandatory: false,
    deadline: '2026-12-31',
    notes: 'Certification target: Q4 2026. Colorado AI Act safe harbor upon certification. 3 minor NCs from internal audit.',
  },
  {
    id: 'c6', name: 'ISO/IEC 42005:2025 (AI Impact Assessment)', shortName: 'ISO 42005', category: 'standard',
    jurisdiction: 'International', status: 'pending', score: 45,
    lastReview: '2026-02-01', nextReview: '2026-05-01',
    openIssues: 8, totalControls: 28, passedControls: 13, mandatory: false,
    deadline: '2026-08-31',
    notes: 'Impact assessments required for EU AI Act conformity. m1/m4 assessments started; m3 highest priority.',
  },
  {
    id: 'c7', name: 'HL7 FHIR R4 / ONC Certification', shortName: 'FHIR/ONC', category: 'interoperability',
    jurisdiction: 'US Federal', status: 'at-risk', score: 72,
    lastReview: '2026-01-15', nextReview: '2026-04-15',
    openIssues: 3, totalControls: 30, passedControls: 22, mandatory: true,
    notes: 'm1/m2/m4 live on FHIR R4. m3 FHIR in progress. m5 planned Q2 2026. Required for EHR integration and CMS reimbursement.',
  },
  {
    id: 'c8', name: 'HHS AI Strategy (Apr 3, 2026 Deadline)', shortName: 'HHS AI Strategy', category: 'regulation',
    jurisdiction: 'US Federal', status: 'in-progress', score: 81,
    lastReview: '2026-02-20', nextReview: '2026-04-03',
    openIssues: 3, totalControls: 35, passedControls: 28, mandatory: true,
    deadline: '2026-04-03',
    notes: 'April 3 deadline for minimum risk management practices: bias mitigation, outcome monitoring, security, human oversight.',
  },
  {
    id: 'c9', name: 'Colorado AI Act', shortName: 'Colorado', category: 'state-law',
    jurisdiction: 'Colorado, US', status: 'at-risk', score: 63,
    lastReview: '2026-02-10', nextReview: '2026-04-10',
    openIssues: 5, totalControls: 22, passedControls: 14, mandatory: true,
    deadline: '2026-06-30',
    notes: 'High-risk AI disclosure, annual impact assessments, anti-bias controls, 3-year record keeping. ISO 42001 = safe harbor.',
  },
  {
    id: 'c10', name: 'Texas RAIGA', shortName: 'Texas', category: 'state-law',
    jurisdiction: 'Texas, US', status: 'compliant', score: 92,
    lastReview: '2026-02-28', nextReview: '2026-08-28',
    openIssues: 1, totalControls: 12, passedControls: 11, mandatory: true,
    notes: 'Written AI disclosure to patients in place (eff. Jan 1, 2026). 1 minor gap: patient signature logging.',
  },
  {
    id: 'c11', name: 'California TFAIA + AB 2013', shortName: 'California', category: 'state-law',
    jurisdiction: 'California, US', status: 'at-risk', score: 68,
    lastReview: '2026-02-15', nextReview: '2026-05-15',
    openIssues: 4, totalControls: 18, passedControls: 12, mandatory: true,
    notes: 'Training data disclosure (AB 2013) partially complete. Generative AI in insurance claims regulation review pending.',
  },
  {
    id: 'c12', name: 'Utah AI Policy Act', shortName: 'Utah', category: 'state-law',
    jurisdiction: 'Utah, US', status: 'compliant', score: 90,
    lastReview: '2026-01-20', nextReview: '2026-07-20',
    openIssues: 1, totalControls: 10, passedControls: 9, mandatory: true,
    notes: '$2,500 per violation for non-disclosure. Disclosure mechanism in place. 1 gap: audit trail for disclosure events.',
  },
];

export const biasMetrics: BiasMetric[] = [
  { modelId: 'm1', modelName: 'Symptom Triage AI', demographic: 'Age 18–25', metric: 'False Negative Rate', value: 0.09, threshold: 0.10, status: 'pass' },
  { modelId: 'm1', modelName: 'Symptom Triage AI', demographic: 'Age 50+', metric: 'False Negative Rate', value: 0.13, threshold: 0.10, status: 'fail' },
  { modelId: 'm1', modelName: 'Symptom Triage AI', demographic: 'Rural Geography', metric: 'Calibration Error', value: 0.06, threshold: 0.07, status: 'pass' },
  { modelId: 'm3', modelName: 'Endometriosis Risk Scorer', demographic: 'Black/African American', metric: 'Calibration Error', value: 0.08, threshold: 0.07, status: 'warn' },
  { modelId: 'm3', modelName: 'Endometriosis Risk Scorer', demographic: 'Hispanic/Latina', metric: 'Equalized Odds', value: 0.19, threshold: 0.15, status: 'fail' },
  { modelId: 'm4', modelName: 'Mental Health Screener', demographic: 'Hispanic/Latina', metric: 'False Negative Rate', value: 0.18, threshold: 0.10, status: 'fail' },
  { modelId: 'm4', modelName: 'Mental Health Screener', demographic: 'Asian', metric: 'False Negative Rate', value: 0.08, threshold: 0.10, status: 'pass' },
  { modelId: 'm4', modelName: 'Mental Health Screener', demographic: 'Age 65+', metric: 'Demographic Parity', value: 0.12, threshold: 0.10, status: 'warn' },
  { modelId: 'm2', modelName: 'Hormone Cycle Predictor', demographic: 'PCOS Cohort', metric: 'MAE (days)', value: 1.8, threshold: 2.0, status: 'pass' },
  { modelId: 'm5', modelName: 'Nutrition Recommendation Engine', demographic: 'Postpartum', metric: 'Coverage Rate', value: 0.97, threshold: 0.95, status: 'pass' },
];

export const useCaseRisks: UseCaseRisk[] = [
  {
    id: 'uc1', useCase: 'Predictive disease risk scoring (diabetes, CVD)',
    fdaClass: 'SaMD', fdaNotes: 'SaMD — requires PCCP + QMSR compliance review',
    euRiskTier: 'High-Risk', stateExposure: 'high',
    stateNotes: 'Disclosure required in TX, CO, UT, CA. Impact assessment required in CO.',
    overallRisk: 'high', pccp: true, hitlRequired: true, disclosureRequired: true,
  },
  {
    id: 'uc2', useCase: 'Lab result interpretation / flagging',
    fdaClass: 'SaMD', fdaNotes: 'Likely FDA regulated as SaMD. Evaluate output claims carefully.',
    euRiskTier: 'High-Risk', stateExposure: 'high',
    stateNotes: 'Disclosure + consent required (PA, OH proposals). TX mandatory.',
    overallRisk: 'critical', pccp: true, hitlRequired: true, disclosureRequired: true,
  },
  {
    id: 'uc3', useCase: 'Care gap identification and outreach',
    fdaClass: 'CDS-non-device', fdaNotes: 'CDS non-device post Jan 2026 CDS guidance revision.',
    euRiskTier: 'High-Risk', stateExposure: 'medium',
    stateNotes: 'Disclosure required. Lower risk than direct clinical decisions.',
    overallRisk: 'medium', pccp: false, hitlRequired: false, disclosureRequired: true,
  },
  {
    id: 'uc4', useCase: 'Administrative automation (scheduling, prior auth)',
    fdaClass: 'Non-device Software', fdaNotes: 'Non-device software — no FDA device regulation.',
    euRiskTier: 'Minimal Risk', stateExposure: 'low',
    stateNotes: 'Standard privacy compliance. Low state law exposure.',
    overallRisk: 'low', pccp: false, hitlRequired: false, disclosureRequired: false,
  },
  {
    id: 'uc5', useCase: 'Personalized prevention recommendations',
    fdaClass: 'CDS-non-device', fdaNotes: 'CDS — evaluate case by case under revised Jan 2026 guidance.',
    euRiskTier: 'High-Risk', stateExposure: 'high',
    stateNotes: 'Disclosure + potential consent in multiple states.',
    overallRisk: 'high', pccp: false, hitlRequired: true, disclosureRequired: true,
  },
  {
    id: 'uc6', useCase: 'Patient-facing chatbot / health coaching',
    fdaClass: 'CDS-non-device', fdaNotes: 'SaMD if therapeutic claims; General Wellness if not. Evaluate carefully.',
    euRiskTier: 'High-Risk', stateExposure: 'high',
    stateNotes: 'Minors protection laws apply. Illinois: licensed professional review required.',
    overallRisk: 'high', pccp: false, hitlRequired: true, disclosureRequired: true,
  },
  {
    id: 'uc7', useCase: 'Wearable data integration for risk monitoring',
    fdaClass: 'General Wellness', fdaNotes: 'General Wellness per Jan 2026 FDA guidance if marketed correctly. No diagnostic claims.',
    euRiskTier: 'Limited Risk', stateExposure: 'low',
    stateNotes: 'Lower exposure if no diagnostic claims made.',
    overallRisk: 'medium', pccp: false, hitlRequired: false, disclosureRequired: false,
  },
];

export const stateDisclosures: StateDisclosure[] = [
  { state: 'Texas', law: 'RAIGA (SB 2060)', requirement: 'Written disclosure to patients when AI is used in healthcare services, prior to or on date of service.', effectiveDate: '2026-01-01', status: 'compliant', penalty: 'Civil penalty per DTPA' },
  { state: 'Colorado', law: 'Colorado AI Act (SB 205)', requirement: 'High-risk AI disclosure, annual impact assessments, anti-bias controls, 3-year record keeping. ISO 42001 = safe harbor.', effectiveDate: '2026-06-30', status: 'in-progress', penalty: 'Colorado AG enforcement' },
  { state: 'California', law: 'TFAIA + AB 2013', requirement: 'Transparency for frontier AI; training data disclosure; generative AI in insurance claims.', effectiveDate: '2026-01-01', status: 'in-progress', penalty: 'California AG enforcement' },
  { state: 'Illinois', law: 'Psychotherapy AI Law', requirement: 'Prohibits AI from making independent therapeutic decisions without licensed professional review.', effectiveDate: '2025-08-01', status: 'compliant', penalty: 'Professional license risk' },
  { state: 'Utah', law: 'Utah AI Policy Act', requirement: 'Disclosure of AI use in regulated sectors including healthcare.', effectiveDate: '2025-05-01', status: 'compliant', penalty: '$2,500 per violation' },
  { state: 'Federal (HHS)', law: 'HHS AI Strategy', requirement: 'Bias mitigation, outcome monitoring, security controls, human oversight for high-impact AI.', effectiveDate: '2026-04-03', status: 'in-progress', penalty: 'HHS program eligibility' },
];

export const roadmapPhases: RoadmapPhase[] = [
  {
    id: 'ph0', phase: 'Phase 0', timeframe: 'Now — Month 3', status: 'complete', completionPct: 100,
    milestone: 'AI risk inventory complete; governance lead appointed',
    actions: [
      { text: 'Classify all AI use cases by FDA/EU/state risk level', done: true },
      { text: 'Appoint Chief AI Officer (CAIO)', done: true },
      { text: 'Build AI Model Registry', done: true },
      { text: 'Map to NIST AI RMF (GOVERN, MAP)', done: true },
      { text: 'Conduct ISO 42001 gap assessment', done: true },
    ],
  },
  {
    id: 'ph1', phase: 'Phase 1', timeframe: 'Months 3–9', status: 'in-progress', completionPct: 62,
    milestone: 'NIST AI RMF compliant; FDA pre-submission meeting held',
    actions: [
      { text: 'Implement NIST AI RMF controls (MEASURE, MANAGE)', done: true },
      { text: 'Deploy bias monitoring pipeline across all models', done: true },
      { text: 'Build explainability layer (m1, m4)', done: true },
      { text: 'Draft and activate patient disclosure protocols (TX, UT)', done: true },
      { text: 'Engage FDA on PCCP for Endometriosis Scorer (m3)', done: true },
      { text: 'Implement 72-hour incident response workflow', done: false },
      { text: 'Complete HHS AI Strategy minimum requirements (Apr 3 deadline)', done: false },
      { text: 'Activate explainability layer for m3', done: false },
    ],
  },
  {
    id: 'ph2', phase: 'Phase 2', timeframe: 'Months 9–18', status: 'upcoming', completionPct: 0,
    milestone: 'ISO 42001 certified; hospital FHIR integrations live',
    actions: [
      { text: 'Pursue ISO/IEC 42001 certification (Schellman audit)', done: false },
      { text: 'Complete ISO 42005 impact assessments for m1, m3, m4', done: false },
      { text: 'Implement HL7 FHIR R4 integrations — all 5 models', done: false },
      { text: 'Launch clinician AI literacy training program', done: false },
      { text: 'Complete Colorado AI Act impact assessments', done: false },
      { text: 'File PCCP with FDA for Endometriosis Scorer', done: false },
    ],
  },
  {
    id: 'ph3', phase: 'Phase 3', timeframe: 'Months 18–30', status: 'upcoming', completionPct: 0,
    milestone: 'Post-market surveillance live; EU-ready documentation',
    actions: [
      { text: 'Post-market surveillance system operational (all models)', done: false },
      { text: 'Real-world evidence collection underway (FDA RWE guidance)', done: false },
      { text: 'EU AI Act conformity assessment (if EU expansion planned)', done: false },
      { text: 'Third-party vendor AI governance audits complete', done: false },
      { text: 'SBOM inventory maintained and updated', done: false },
    ],
  },
  {
    id: 'ph4', phase: 'Phase 4', timeframe: 'Ongoing', status: 'upcoming', completionPct: 0,
    milestone: 'Continuous governance maturity; reimbursement evidence building',
    actions: [
      { text: 'Quarterly bias reviews (all production models)', done: false },
      { text: 'Annual ISO 42001 surveillance audits', done: false },
      { text: 'State law change monitoring (IAPP + Manatt trackers)', done: false },
      { text: 'Maintain SBOM and cybersecurity posture', done: false },
      { text: 'Expand RWE database for CMS ACCESS Model reimbursement', done: false },
      { text: 'Participate in TEMPO Pilot (FDA + CMS)', done: false },
    ],
  },
];

export const governancePrinciples: GovernancePrinciple[] = [
  { id: 'gp1', number: 1, title: 'Transparency', status: 'partial',
    description: 'Patients and clinicians must know when AI is influencing a decision. Disclose at every touchpoint. Document all model cards.',
    evidence: 'TX/UT disclosure live. CO/CA in progress. Model cards drafted for m1, m2, m4.',
  },
  { id: 'gp2', number: 2, title: 'Human Oversight', status: 'implemented',
    description: 'No AI makes a final clinical decision. Every high-risk recommendation requires clinician review with documented override capability.',
    evidence: 'HITL policy active. Override logging live on m1, m4. m3 incident triggered remediation.',
  },
  { id: 'gp3', number: 3, title: 'Fairness & Bias Control', status: 'partial',
    description: 'Continuously monitor model performance across all patient demographic groups. Report disparities. Retrain when bias thresholds are exceeded.',
    evidence: '3 active bias failures under remediation (m1 Age 50+, m3 Hispanic/Latina, m4 Hispanic/Latina).',
  },
  { id: 'gp4', number: 4, title: 'Data Governance', status: 'partial',
    description: 'Full lineage of training and inference data. Patients own their data. HIPAA is the floor. FHIR interoperability mandatory.',
    evidence: 'HIPAA 96% compliant. FHIR live on 3/5 models. AB 2013 data lineage in progress.',
  },
  { id: 'gp5', number: 5, title: 'Security by Design', status: 'partial',
    description: 'Threat modeling, SBOM, update mechanisms embedded from Day 1. Regular penetration testing. AI-specific cyber insurance riders.',
    evidence: 'SBOM policy active. Threat modeling complete for m1/m3/m4. Pen test Q2 2026.',
  },
  { id: 'gp6', number: 6, title: 'Explainability', status: 'partial',
    description: 'Every AI output has a plain-language explanation and confidence interval visible to the clinician, designed for clinical workflow.',
    evidence: 'Explainability live on m1, m2, m4, m5. m3 planned (blocking production release).',
  },
  { id: 'gp7', number: 7, title: 'Continuous Improvement', status: 'partial',
    description: 'Post-market surveillance is not optional. Maintain real-world performance monitoring, incident reporting, and formal corrective action process.',
    evidence: 'Drift monitoring live. 72h incident policy active. RWE collection policy in draft.',
  },
];

export const dashboardStats: DashboardStats = {
  totalModels: 5,
  activeModels: 4,
  highRiskModels: 2,
  activePolicies: 10,
  openAuditFlags: 2,
  avgBiasScore: 17.8,
  complianceRate: 78,
  iso42001Status: 'in-progress',
  pccpApproved: 0,
  fhirLive: 3,
  openIncidents: 1,
  stateComplianceGaps: 3,
};

export const biasOverTime = [
  { month: 'Oct', avg: 24 },
  { month: 'Nov', avg: 21 },
  { month: 'Dec', avg: 20 },
  { month: 'Jan', avg: 19 },
  { month: 'Feb', avg: 18 },
  { month: 'Mar', avg: 17.8 },
];

export const complianceOverTime = [
  { month: 'Oct', score: 71 },
  { month: 'Nov', score: 74 },
  { month: 'Dec', score: 78 },
  { month: 'Jan', score: 79 },
  { month: 'Feb', score: 81 },
  { month: 'Mar', score: 78 },
];
