import type { AIModel, Policy, AuditEntry, ComplianceFramework, BiasMetric, DashboardStats } from '@/types';

export const models: AIModel[] = [
  {
    id: 'm1',
    name: 'Symptom Triage AI',
    version: '2.3.1',
    status: 'production',
    purpose: 'Triage patient-reported symptoms for priority routing',
    riskLevel: 'high',
    owner: 'Clinical AI Team',
    deployedAt: '2025-09-15',
    lastAudit: '2026-02-01',
    biasScore: 18,
    accuracyScore: 91,
    fairnessScore: 87,
  },
  {
    id: 'm2',
    name: 'Hormone Cycle Predictor',
    version: '1.8.0',
    status: 'production',
    purpose: 'Predict hormonal cycle phases from wearable data',
    riskLevel: 'medium',
    owner: 'FemTech Research',
    deployedAt: '2025-11-02',
    lastAudit: '2026-01-20',
    biasScore: 11,
    accuracyScore: 88,
    fairnessScore: 93,
  },
  {
    id: 'm3',
    name: 'Endometriosis Risk Scorer',
    version: '1.1.4',
    status: 'staging',
    purpose: 'Estimate endometriosis likelihood from reported symptoms',
    riskLevel: 'critical',
    owner: 'Clinical AI Team',
    deployedAt: '2026-01-10',
    lastAudit: '2026-02-28',
    biasScore: 31,
    accuracyScore: 79,
    fairnessScore: 74,
  },
  {
    id: 'm4',
    name: 'Mental Health Screener',
    version: '3.0.0',
    status: 'production',
    purpose: 'PHQ-9 / GAD-7 guided screening assistant',
    riskLevel: 'high',
    owner: 'Behavioral Health Squad',
    deployedAt: '2025-07-20',
    lastAudit: '2026-02-10',
    biasScore: 22,
    accuracyScore: 85,
    fairnessScore: 81,
  },
  {
    id: 'm5',
    name: 'Nutrition Recommendation Engine',
    version: '2.0.2',
    status: 'production',
    purpose: 'Personalized dietary guidance for women\'s health goals',
    riskLevel: 'low',
    owner: 'Wellness Team',
    deployedAt: '2025-06-01',
    lastAudit: '2026-01-05',
    biasScore: 7,
    accuracyScore: 83,
    fairnessScore: 95,
  },
];

export const policies: Policy[] = [
  {
    id: 'p1',
    title: 'AI Model Risk Classification Policy',
    category: 'Risk Management',
    status: 'active',
    version: '1.2',
    owner: 'Chief AI Officer',
    createdAt: '2025-04-01',
    updatedAt: '2026-01-15',
    description: 'Defines risk tiers for all AI models based on clinical impact, data sensitivity, and patient exposure.',
    applicableModels: ['m1', 'm2', 'm3', 'm4', 'm5'],
  },
  {
    id: 'p2',
    title: 'Bias Testing & Fairness Requirements',
    category: 'Fairness',
    status: 'active',
    version: '2.0',
    owner: 'Ethics & Fairness Board',
    createdAt: '2025-06-10',
    updatedAt: '2025-12-20',
    description: 'Mandates demographic parity, equalized odds, and calibration testing before production deployment.',
    applicableModels: ['m1', 'm3', 'm4'],
  },
  {
    id: 'p3',
    title: 'Patient Data Usage & Consent Policy',
    category: 'Privacy',
    status: 'active',
    version: '3.1',
    owner: 'Privacy & Legal',
    createdAt: '2024-11-01',
    updatedAt: '2026-02-01',
    description: 'Governs how patient-derived data is used for model training, inference, and retraining pipelines.',
    applicableModels: ['m1', 'm2', 'm3', 'm4', 'm5'],
  },
  {
    id: 'p4',
    title: 'Human-in-the-Loop Override Requirements',
    category: 'Human Oversight',
    status: 'active',
    version: '1.0',
    owner: 'Clinical AI Team',
    createdAt: '2025-08-15',
    updatedAt: '2025-08-15',
    description: 'Requires clinician review for all high-risk AI recommendations before surfacing to patients.',
    applicableModels: ['m1', 'm3', 'm4'],
  },
  {
    id: 'p5',
    title: 'Model Drift Monitoring Standard',
    category: 'Monitoring',
    status: 'active',
    version: '1.1',
    owner: 'MLOps Team',
    createdAt: '2025-09-01',
    updatedAt: '2025-11-30',
    description: 'Sets thresholds and cadence for data drift and performance degradation alerts across production models.',
    applicableModels: ['m1', 'm2', 'm4', 'm5'],
  },
  {
    id: 'p6',
    title: 'Explainability Disclosure Standard',
    category: 'Transparency',
    status: 'draft',
    version: '0.3',
    owner: 'Product & Ethics',
    createdAt: '2026-02-01',
    updatedAt: '2026-03-01',
    description: 'Draft policy requiring plain-language explanations of AI-driven recommendations presented to patients.',
    applicableModels: ['m1', 'm3', 'm4'],
  },
];

export const auditEntries: AuditEntry[] = [
  {
    id: 'a1',
    timestamp: '2026-03-11T14:32:00Z',
    modelId: 'm3',
    modelName: 'Endometriosis Risk Scorer',
    action: 'High-risk score surfaced without clinician review',
    actor: 'System (automated)',
    outcome: 'Flagged — override policy violated',
    riskFlag: true,
    details: 'Patient received a CRITICAL risk score directly via app notification without required HITL review step.',
  },
  {
    id: 'a2',
    timestamp: '2026-03-11T09:15:00Z',
    modelId: 'm1',
    modelName: 'Symptom Triage AI',
    action: 'Model retrained on Q1 2026 data batch',
    actor: 'MLOps Pipeline',
    outcome: 'Success — bias re-evaluation passed',
    riskFlag: false,
    details: 'Quarterly retraining completed. Bias score improved from 21 to 18. Fairness thresholds all passed.',
  },
  {
    id: 'a3',
    timestamp: '2026-03-10T16:45:00Z',
    modelId: 'm4',
    modelName: 'Mental Health Screener',
    action: 'Demographic disparity detected in PHQ-9 scoring',
    actor: 'Bias Monitor (automated)',
    outcome: 'Warning issued — under review',
    riskFlag: true,
    details: 'Hispanic/Latina cohort showing 12% higher false-negative rate vs overall population. Investigation initiated.',
  },
  {
    id: 'a4',
    timestamp: '2026-03-09T11:00:00Z',
    modelId: 'm2',
    modelName: 'Hormone Cycle Predictor',
    action: 'Policy P3 consent audit completed',
    actor: 'Privacy & Legal',
    outcome: 'Compliant',
    riskFlag: false,
    details: 'Annual consent audit for training data usage confirmed all records have valid opt-in consent.',
  },
  {
    id: 'a5',
    timestamp: '2026-03-08T08:20:00Z',
    modelId: 'm5',
    modelName: 'Nutrition Recommendation Engine',
    action: 'Performance drift alert triggered',
    actor: 'Drift Monitor (automated)',
    outcome: 'Acknowledged — scheduled review',
    riskFlag: false,
    details: 'Accuracy dropped 2.1% over 30 days. Within acceptable range but scheduled for review next sprint.',
  },
];

export const complianceFrameworks: ComplianceFramework[] = [
  {
    id: 'c1',
    name: 'HIPAA',
    status: 'compliant',
    score: 96,
    lastReview: '2026-02-15',
    nextReview: '2026-08-15',
    openIssues: 1,
    totalControls: 54,
    passedControls: 52,
  },
  {
    id: 'c2',
    name: 'FDA AI/ML SaMD Guidance',
    status: 'at-risk',
    score: 71,
    lastReview: '2026-01-20',
    nextReview: '2026-04-20',
    openIssues: 5,
    totalControls: 38,
    passedControls: 27,
  },
  {
    id: 'c3',
    name: 'EU AI Act (High-Risk)',
    status: 'at-risk',
    score: 68,
    lastReview: '2026-02-28',
    nextReview: '2026-05-28',
    openIssues: 7,
    totalControls: 45,
    passedControls: 31,
  },
  {
    id: 'c4',
    name: 'NIST AI RMF',
    status: 'compliant',
    score: 88,
    lastReview: '2026-01-10',
    nextReview: '2026-07-10',
    openIssues: 2,
    totalControls: 50,
    passedControls: 44,
  },
];

export const biasMetrics: BiasMetric[] = [
  { modelId: 'm1', modelName: 'Symptom Triage AI', demographic: 'Age 18–25', metric: 'False Negative Rate', value: 0.09, threshold: 0.10, status: 'pass' },
  { modelId: 'm1', modelName: 'Symptom Triage AI', demographic: 'Age 50+', metric: 'False Negative Rate', value: 0.13, threshold: 0.10, status: 'fail' },
  { modelId: 'm3', modelName: 'Endometriosis Risk Scorer', demographic: 'Black/African American', metric: 'Calibration Error', value: 0.08, threshold: 0.07, status: 'warn' },
  { modelId: 'm3', modelName: 'Endometriosis Risk Scorer', demographic: 'Hispanic/Latina', metric: 'Equalized Odds', value: 0.19, threshold: 0.15, status: 'fail' },
  { modelId: 'm4', modelName: 'Mental Health Screener', demographic: 'Hispanic/Latina', metric: 'False Negative Rate', value: 0.18, threshold: 0.10, status: 'fail' },
  { modelId: 'm4', modelName: 'Mental Health Screener', demographic: 'Asian', metric: 'False Negative Rate', value: 0.08, threshold: 0.10, status: 'pass' },
  { modelId: 'm2', modelName: 'Hormone Cycle Predictor', demographic: 'PCOS Cohort', metric: 'MAE (days)', value: 1.8, threshold: 2.0, status: 'pass' },
  { modelId: 'm5', modelName: 'Nutrition Recommendation Engine', demographic: 'Postpartum', metric: 'Coverage Rate', value: 0.97, threshold: 0.95, status: 'pass' },
];

export const dashboardStats: DashboardStats = {
  totalModels: 5,
  activeModels: 4,
  highRiskModels: 2,
  activePolicies: 5,
  openAuditFlags: 2,
  avgBiasScore: 17.8,
  complianceRate: 81,
};

export const biasOverTime = [
  { month: 'Oct', avg: 24 },
  { month: 'Nov', avg: 21 },
  { month: 'Dec', avg: 20 },
  { month: 'Jan', avg: 19 },
  { month: 'Feb', avg: 18 },
  { month: 'Mar', avg: 17.8 },
];

export const complianceOverTime = [
  { month: 'Oct', score: 71 },
  { month: 'Nov', score: 74 },
  { month: 'Dec', score: 78 },
  { month: 'Jan', score: 79 },
  { month: 'Feb', score: 81 },
  { month: 'Mar', score: 81 },
];
